name: express_wash
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  introduction_screen: ^3.0.0
  hexcolor: ^2.0.6
  otp_text_field: ^1.1.2
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon_app.png
    - assets/icons/icon.png
    - assets/assist.png
    - assets/del.png
    - assets/first.png
    - assets/deliver.png